<a href="https://colab.research.google.com/github/manasamadgul/Pytorch_Fundamentals/blob/main/Exercises_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Create a random tensor with shape (7, 7).


In [1]:
import torch
tensor = torch.rand(7, 7)
print(tensor)

tensor([[0.3679, 0.7224, 0.5724, 0.3712, 0.9331, 0.9794, 0.5155],
        [0.6822, 0.3199, 0.5676, 0.9213, 0.9917, 0.9193, 0.4502],
        [0.5984, 0.6361, 0.5837, 0.2503, 0.6311, 0.5780, 0.5514],
        [0.7117, 0.4076, 0.8097, 0.4352, 0.9588, 0.2248, 0.7928],
        [0.1210, 0.5274, 0.7006, 0.2602, 0.1693, 0.3067, 0.7484],
        [0.9862, 0.2833, 0.8452, 0.1370, 0.7346, 0.6986, 0.3921],
        [0.0658, 0.4283, 0.5319, 0.7635, 0.1708, 0.8073, 0.7660]])


#Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).


In [2]:
tensor2 = torch.rand(1, 7)
result = torch.mm(tensor, tensor2.T)
print(result)


tensor([[1.6253],
        [1.7519],
        [1.4928],
        [1.7772],
        [0.9736],
        [1.8863],
        [0.9695]])


In [5]:
#Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(0)
tensor = torch.rand(7,7)
print(tensor)
torch.manual_seed(0)
tensor2 = torch.rand(1,7)
print(tensor2)
result = torch.mm(tensor, tensor2.T)
print(result)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


#Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234

In [5]:
#set random seed on GPU
new_var = torch.cuda.manual_seed(1234)
new_var

In [3]:
#Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
import torch
#set random seed
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

x = torch.rand(2,3).to(device)
print(x)
torch.manual_seed(1234)
y = torch.rand(2,3).to(device)
print(y)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


#Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).


In [5]:
#mm - alias for matrix multiplication
z = torch.mm(x,y.T)
z,z.shape

(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]], device='cuda:0'),
 torch.Size([2, 2]))

#Find the maximum and minimum values of the output of 7.


In [6]:
max = z.max()
min = z.min()
max,min

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

#Find the maximum and minimum index values of the output of 7.


In [7]:
maxindex = z.argmax()
minindex = z.argmin()
maxindex,minindex

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

In [10]:
#Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

import torch
torch.manual_seed(7)
tensor1 = torch.rand(size =(1, 1, 1, 10))
print(tensor1, tensor1.shape)
tensor2 = tensor1.squeeze()
print(tensor2, tensor2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


In [15]:
#torch.manual_seed(2)
print(torch.rand(2))


tensor([0.6371, 0.4745])
