Pytorch lessons:https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())


2.4.0+cu121
False


##Introduction to Tensors
Tensors are created using torch.tensor()

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#vector tensor
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [4]:
vector.ndim

1

In [5]:
vector.shape

torch.Size([2])

In [6]:
#matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
MATRIX[0]

tensor([7, 8])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
#Tensor
TENSOR = torch.tensor([[[1,2,3,4],[3,4,5,4],[1,4,5,6]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [3, 4, 5, 4],
         [1, 4, 5, 6]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 4])

In [13]:
TENSOR = torch.tensor([[[1,2],[3,4],[1,2],[3,4],[1,2],[3,4]]])
TENSOR

tensor([[[1, 2],
         [3, 4],
         [1, 2],
         [3, 4],
         [1, 2],
         [3, 4]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 6, 2])

In [16]:
TENSOR = torch.rand(5,4,4)
TENSOR,TENSOR.ndim,TENSOR.shape

(tensor([[[0.8146, 0.9094, 0.9921, 0.0201],
          [0.7060, 0.4518, 0.7704, 0.1925],
          [0.5904, 0.4766, 0.7164, 0.9079],
          [0.7932, 0.8177, 0.0210, 0.3993]],
 
         [[0.0336, 0.9189, 0.7937, 0.3935],
          [0.8920, 0.9472, 0.1193, 0.5547],
          [0.1705, 0.9372, 0.9664, 0.2774],
          [0.8203, 0.5277, 0.1190, 0.2016]],
 
         [[0.5422, 0.8555, 0.1961, 0.1594],
          [0.2417, 0.0564, 0.9956, 0.2612],
          [0.5425, 0.9974, 0.3648, 0.4811],
          [0.1924, 0.1787, 0.6183, 0.5065]],
 
         [[0.6623, 0.1248, 0.3829, 0.0523],
          [0.6777, 0.9584, 0.8795, 0.9621],
          [0.8768, 0.7142, 0.8672, 0.7127],
          [0.2864, 0.6878, 0.9205, 0.7987]],
 
         [[0.5244, 0.8248, 0.2230, 0.5784],
          [0.9783, 0.9146, 0.0885, 0.8241],
          [0.2533, 0.9321, 0.7961, 0.5510],
          [0.8309, 0.5465, 0.9003, 0.0483]]]),
 3,
 torch.Size([5, 4, 4]))

### Manipulating Tensors
 *addition
 *sub
 *multi
 *division
 *Matrix multiplication



In [17]:
#create a tensor and add 20 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [18]:
tensor*10

tensor([10, 20, 30])

In [19]:
tensor -1

tensor([0, 1, 2])

In [20]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [21]:
#Matrix Mulitplication
 # 1.way 1 : element wise multiplication (each element by a scalar))
 # 2.way 2 : Matrix multiplication/dot product

In [22]:
#way 1 : element wise
tensor = torch.tensor([1,2,3])
tensor*tensor

tensor([1, 4, 9])

In [23]:
#way2 dot product or matrix multiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 360 µs, sys: 57 µs, total: 417 µs
Wall time: 24.8 ms


tensor(14)



*   List item
*   List item



In [24]:
tensor1 = torch.rand((3,3), dtype=torch.float16)
print(tensor1)
print(tensor1.ndim)
tensor2 = torch.rand((3,2), dtype= torch.float16)
print(tensor2)
print(tensor2.ndim)
torch.matmul(tensor1,tensor2).shape

tensor([[0.2856, 0.4307, 0.5410],
        [0.6235, 0.5400, 0.7192],
        [0.4907, 0.6299, 0.1045]], dtype=torch.float16)
2
tensor([[0.6963, 0.8384],
        [0.7651, 0.1943],
        [0.7510, 0.9429]], dtype=torch.float16)
2


torch.Size([3, 2])

In [27]:
#transpose can be used to change the shape of a matrix. this can be very useful when we are doing matrix multiplication and size errors are faced
#matrix multiplication can also be written as matmul,mm(short form) or @
#.T --> transpose operation
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
torch.matmul(tensor_A,tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [43]:
#to find the positional min and max we use argmin and argmax. we just want to know the position where we have min and max values
x =torch.tensor([29,10,20,30,50,88,79,80])
x.argmin()


tensor(1)

In [44]:
x[0]

tensor(29)

In [45]:
x.argmax()

tensor(5)

In [46]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [47]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [48]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [49]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [50]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found
