In [1]:
import numpy as np

In [33]:
#dot takes 2 arrays (1-D) and it provides scalar value as output

arr1 = np.array([1,"ABC",3])
arr2 = np.array([1,2,3])
arraydot = np.dot(arr1,arr2)
print(arr1)
print(arr2)
print(arraydot)


ValueError: data type must provide an itemsize

In [47]:
#dot takes 2 arrays (2-D) and it provides scalar value as output
arr3 = np.array([[1,2],[1,2]])
print(type(arr3))
arr4 = np.array([[1,2,3,4],[1,2,3,4]])
print(type(arr4))
arraydot2d = np.dot(arr3,arr4)
print(arr3)
print(arr4)
print(arraydot2d)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[1 2]
 [1 2]]
[[1 2 3 4]
 [1 2 3 4]]
[[ 3  6  9 12]
 [ 3  6  9 12]]


In [38]:
arr3 = np.array([[1,2],[1,2],[1,2]])
print(type(arr3))
arr4 = np.array([[1,2,3],[1,2,3]])
print(type(arr4))
arraydot2d = np.dot(arr3,arr4)
print("Dot:")
print(arraydot2d)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[1 2]
 [1 2]
 [1 2]]
[[1 2 3]
 [1 2 3]]
Dot:
[[3 6 9]
 [3 6 9]
 [3 6 9]]


In [44]:
#dot takes 2 arrays (1-D) and it provides scalar value as output

arr1 = np.array([[1,2],[1,2]])
arr2 = np.array([[1,2],[1,2]])
arraydot = np.dot(arr1,arr2)
print(arr1)
print(arr2)
print(arraydot)

[[1 2]
 [1 2]]
[[1 2]
 [1 2]]
[[3 6]
 [3 6]]


In [57]:
#random.rand generates random array values
arrayrand1 = np.random.rand(2,3)
print(arrayrand1)
arrayrand2 = np.random.rand(3,2)
print(arrayrand2)
dot = np.dot(arrayrand1,arrayrand2)
print(dot)

[[0.45648284 0.68356848 0.101974  ]
 [0.9323733  0.8386289  0.63390135]]
[[0.28142706 0.87285742]
 [0.81603685 0.44349354]
 [0.43515275 0.32953457]]
[[0.73065796 0.73520659]
 [1.22259108 1.39464786]]


In [6]:
arrayrand1 = np.random.rand(1,3)
print(arrayrand1)
arrayrand2 = np.random.rand(3,1)
print(arrayrand2)
dot = np.dot(arrayrand1,arrayrand2)
print(dot)

[[0.88106414 0.04037663 0.94634191]]
[[0.12012503]
 [0.10858078]
 [0.88879712]]
[[0.95132794]]


In [18]:
x1 = np.random.uniform(7,10,size=(2,3))
print(x1)
x2 = np.random.uniform(7,10,size=(3,4))
print(x2)
x3 =np.dot(x1,x2)
print(x3)


[[9.56630235 9.75181577 8.22447228]
 [8.20393823 9.47890113 9.74225293]]
[[7.72367042 7.11668071 7.86767068 7.31799844]
 [8.26520478 7.33588677 8.99214548 7.05976523]
 [9.19428365 7.55360067 8.28768761 9.31303203]]
[[230.10585181 201.74291512 231.11611962 215.44648931]
 [231.28261079 201.51004271 230.52229112 217.68513734]]
